# Generated by Django 2.2 on 2020-04-15 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='website',
            field=models.URLField(default='blank'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='jobtitle',
            field=models.CharField(default='blank', max_length=150),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(default='blank', upload_to='uploads/profiles/'),
        ),
    ]
