# Generated by Django 2.2 on 2020-04-16 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0006_auto_20200416_0335'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatResume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='Title')),
            ],
        ),
        migrations.CreateModel(
            name='MyResume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('year', models.DateField()),
                ('current', models.BooleanField(default=False)),
                ('desc', models.TextField()),
                ('icon', models.CharField(max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myprofile.CatResume', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'MyResume',
                'verbose_name_plural': 'MyResumes',
            },
        ),
    ]
