# Generated by Django 2.2 on 2020-04-16 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0007_catresume_myresume'),
    ]

    operations = [
        migrations.AddField(
            model_name='myresume',
            name='name',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
